import type { Business, Review } from "@/types";

export const FALLBACK_BUSINESSES: Business[] = [
  {
    id: 1,
    name: "Mr. Desert Jaisalmer",
    slug: "mr-desert",
    description: "Mr. Desert Jaisalmer is the premier tourism brand in Jaisalmer, Rajasthan, offering world-class travel experiences. From luxury desert camps and heritage hotels to thrilling camel safaris and curated Rajasthan tour packages, we provide authentic and unforgettable journeys through the golden city.",
    short_description: "Premier tourism brand offering hotels, desert camps, safaris & Rajasthan tour packages.",
    logo_url: null,
    hero_image_url: "/images/dheeraj/mr-desert-alley.webp",
    website_url: "https://mrdesertjaisalmer.in",
    booking_url: "https://mrdesertjaisalmer.in/booking",
    contact_phone: "+91-9829038039",
    contact_email: "info@mrdesertjaisalmer.in",
    whatsapp_number: "+919829038039",
    address: "Near Sam Sand Dunes, Jaisalmer, Rajasthan 345001",
    google_maps_url: "https://maps.google.com/?q=Mr+Desert+Jaisalmer",
    google_maps_embed: null,
    average_rating: 4.9,
    total_reviews: 350,
    is_active: true,
    order: 1,
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
  },
  {
    id: 2,
    name: "Elite Castle Jaisalmer",
    slug: "elite-castle",
    description: "Elite Castle Jaisalmer is a luxury heritage hotel located in the heart of Jaisalmer. Combining Rajput-era architecture with modern luxury, we offer beautifully appointed rooms, rooftop dining with fort views, and warm Rajasthani hospitality.",
    short_description: "Luxury heritage hotel in Jaisalmer with premium rooms & rooftop dining.",
    logo_url: null,
    hero_image_url: "/images/official/elite-castle-story.webp",
    website_url: "https://elitecastlejaisalmer.com",
    booking_url: "https://elitecastlejaisalmer.com/booking",
    contact_phone: "+91-9829038039",
    contact_email: "info@elitecastlejaisalmer.com",
    whatsapp_number: "+919829038039",
    address: "Near Jaisalmer Fort, Jaisalmer, Rajasthan 345001",
    google_maps_url: "https://maps.google.com/?q=Elite+Castle+Jaisalmer",
    google_maps_embed: null,
    average_rating: 4.8,
    total_reviews: 280,
    is_active: true,
    order: 2,
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
  },
  {
    id: 3,
    name: "Happy Adventure Camp Jaisalmer",
    slug: "happy-adventure",
    description: "Happy Adventure Camp Jaisalmer offers the ultimate luxury desert camping experience in the Thar Desert. Enjoy traditional Rajasthani cultural performances, camel safaris at sunset, jeep safaris across golden dunes, and comfortable Swiss tents.",
    short_description: "Luxury desert camp with cultural programs, camel safaris & overnight camping.",
    logo_url: null,
    hero_image_url: "/images/dheeraj/happy-camp-night.webp",
    website_url: "https://happyadventurecampjaisalmer.com",
    booking_url: "https://happyadventurecampjaisalmer.com/booking",
    contact_phone: "+91-9829038039",
    contact_email: "info@happyadventurecampjaisalmer.com",
    whatsapp_number: "+919829038039",
    address: "Sam Sand Dunes, Jaisalmer, Rajasthan 345001",
    google_maps_url: "https://maps.google.com/?q=Happy+Adventure+Camp+Jaisalmer",
    google_maps_embed: null,
    average_rating: 4.9,
    total_reviews: 420,
    is_active: true,
    order: 3,
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
  },
  {
    id: 4,
    name: "Elite India Tour Planner",
    slug: "tour-planner",
    description: "Elite India Tour Planner specializes in crafting customized travel experiences across Rajasthan and India. From private luxury tours to budget-friendly group packages, we handle every detail.",
    short_description: "Professional Rajasthan tour planning with customized packages.",
    logo_url: null,
    hero_image_url: "/images/dheeraj/dheeraj-purohit.webp",
    website_url: "https://eliteindiatourplanner.com",
    booking_url: "https://eliteindiatourplanner.com/booking",
    contact_phone: "+91-9829038039",
    contact_email: "info@eliteindiatourplanner.com",
    whatsapp_number: "+919829038039",
    address: "Jaisalmer, Rajasthan 345001",
    google_maps_url: "https://maps.google.com/?q=Elite+India+Tour+Planner",
    google_maps_embed: null,
    average_rating: 4.9,
    total_reviews: 190,
    is_active: true,
    order: 4,
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
  },
];

export const FALLBACK_REVIEWS: Review[] = [
  {
    id: 101,
    business_id: 1,
    business_name: "Mr. Desert Jaisalmer",
    business_slug: "mr-desert",
    guest_name: "Rajesh Sharma",
    guest_email: null,
    guest_photo_url: null,
    country: "India",
    city: "Mumbai",
    visit_date: "2026-01-15",
    overall_rating: 5,
    staff_rating: 5,
    cleanliness_rating: 5,
    food_rating: 5,
    location_rating: 5,
    experience_rating: 5,
    value_for_money: 5,
    title: "Best desert experience in Jaisalmer!",
    content: "Mr. Desert made our Jaisalmer trip unforgettable. The camel safari at sunset was magical, and the camp staff were incredibly welcoming. Highly recommended!",
    is_recommended: true,
    is_verified: true,
    is_featured: true,
    is_published: true,
    is_pinned: true,
    status: "approved",
    review_source: "website",
    helpful_count: 14,
    media: [],
    reply: {
      id: 1,
      content: "Thank you, Rajesh! We're thrilled you enjoyed the desert experience. Hope to welcome you back soon!",
      created_at: "2026-02-11T10:00:00Z",
      updated_at: "2026-02-11T10:00:00Z",
    },
    created_at: "2026-02-10T10:00:00Z",
    updated_at: "2026-02-10T10:00:00Z",
  },
  {
    id: 102,
    business_id: 1,
    business_name: "Mr. Desert Jaisalmer",
    business_slug: "mr-desert",
    guest_name: "Sarah Johnson",
    guest_email: null,
    guest_photo_url: null,
    country: "United Kingdom",
    city: "London",
    visit_date: "2026-01-20",
    overall_rating: 5,
    staff_rating: 5,
    cleanliness_rating: 5,
    food_rating: 5,
    location_rating: 5,
    experience_rating: 5,
    value_for_money: 5,
    title: "Magical stay in the desert",
    content: "Staying with Mr. Desert was the highlight of our Rajasthan trip. The luxury tents were far better than expected, and the staff went above and beyond.",
    is_recommended: true,
    is_verified: true,
    is_featured: true,
    is_published: true,
    is_pinned: false,
    status: "approved",
    review_source: "website",
    helpful_count: 9,
    media: [],
    reply: null,
    created_at: "2026-02-12T14:30:00Z",
    updated_at: "2026-02-12T14:30:00Z",
  },
  {
    id: 103,
    business_id: 2,
    business_name: "Elite Castle Jaisalmer",
    business_slug: "elite-castle",
    guest_name: "Amit Kumar",
    guest_email: null,
    guest_photo_url: null,
    country: "India",
    city: "Delhi",
    visit_date: "2026-02-01",
    overall_rating: 5,
    staff_rating: 5,
    cleanliness_rating: 5,
    food_rating: 5,
    location_rating: 5,
    experience_rating: 5,
    value_for_money: 5,
    title: "Royal treatment at its finest",
    content: "Elite Castle is a gem in Jaisalmer! The hotel architecture is stunning, the rooms are spacious, and the rooftop restaurant offers an amazing view of the fort.",
    is_recommended: true,
    is_verified: true,
    is_featured: true,
    is_published: true,
    is_pinned: false,
    status: "approved",
    review_source: "website",
    helpful_count: 11,
    media: [],
    reply: null,
    created_at: "2026-02-15T09:15:00Z",
    updated_at: "2026-02-15T09:15:00Z",
  },
  {
    id: 104,
    business_id: 3,
    business_name: "Happy Adventure Camp Jaisalmer",
    business_slug: "happy-adventure",
    guest_name: "Vikram Singh",
    guest_email: null,
    guest_photo_url: null,
    country: "India",
    city: "Jaipur",
    visit_date: "2026-02-05",
    overall_rating: 5,
    staff_rating: 5,
    cleanliness_rating: 5,
    food_rating: 5,
    location_rating: 5,
    experience_rating: 5,
    value_for_money: 5,
    title: "Ultimate desert camping!",
    content: "Happy Adventure Camp exceeded all expectations. The luxury tents are incredibly comfortable. Camel safari at sunset was the perfect end to the day!",
    is_recommended: true,
    is_verified: true,
    is_featured: true,
    is_published: true,
    is_pinned: false,
    status: "approved",
    review_source: "website",
    helpful_count: 18,
    media: [],
    reply: null,
    created_at: "2026-02-18T18:20:00Z",
    updated_at: "2026-02-18T18:20:00Z",
  },
  {
    id: 105,
    business_id: 4,
    business_name: "Elite India Tour Planner",
    business_slug: "tour-planner",
    guest_name: "Rohan Mehta",
    guest_email: null,
    guest_photo_url: null,
    country: "India",
    city: "Mumbai",
    visit_date: "2026-02-10",
    overall_rating: 5,
    staff_rating: 5,
    cleanliness_rating: 5,
    food_rating: 5,
    location_rating: 5,
    experience_rating: 5,
    value_for_money: 5,
    title: "Flawless Rajasthan trip planning",
    content: "Elite India Tour Planner organized our 10-day Rajasthan trip and everything was flawless. From hotel bookings to guided tours, every detail was taken care of.",
    is_recommended: true,
    is_verified: true,
    is_featured: true,
    is_published: true,
    is_pinned: false,
    status: "approved",
    review_source: "website",
    helpful_count: 7,
    media: [],
    reply: null,
    created_at: "2026-02-20T11:45:00Z",
    updated_at: "2026-02-20T11:45:00Z",
  },
];
