import type { Business, Review, ContentItem } from "@/types";

export const FALLBACK_BUSINESSES: Business[] = [
  {
    id: 1,
    name: "Mr. Desert Jaisalmer",
    slug: "mr-desert",
    description: "Mr. Desert Jaisalmer is the premier tourism brand in Jaisalmer, Rajasthan, offering world-class travel experiences. From luxury desert camps and heritage hotels to thrilling camel safaris and curated Rajasthan tour packages, we provide authentic and unforgettable journeys through the golden city.",
    short_description: "Premier tourism brand offering hotels, desert camps, safaris & Rajasthan tour packages.",
    logo_url: "/businesses/mr-desert/logo.png",
    hero_image_url: "/businesses/mr-desert/6-scaled-e1756826347412.webp",
    website_url: "https://mrdesertjaisalmer.in",
    booking_url: "https://mrdesertjaisalmer.in/booking",
    contact_phone: "+91-9829038039",
    contact_email: "info@mrdesertjaisalmer.in",
    whatsapp_number: "+919829038039",
    address: "Near Sam Sand Dunes, Jaisalmer, Rajasthan 345001",
    google_maps_url: "https://maps.google.com/?q=Mr+Desert+Jaisalmer",
    google_maps_embed: null,
    average_rating: 4.9,
    total_reviews: 350,
    is_active: true,
    order: 1,
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
  },
  {
    id: 2,
    name: "Elite Castle Jaisalmer",
    slug: "elite-castle",
    description: "Elite Castle Jaisalmer is a luxury heritage hotel located in the heart of Jaisalmer. Combining Rajput-era architecture with modern luxury, we offer beautifully appointed rooms, rooftop dining with fort views, and warm Rajasthani hospitality.",
    short_description: "Luxury heritage hotel in Jaisalmer with premium rooms & rooftop dining.",
    logo_url: null,
    hero_image_url: "/businesses/elite-castle/WhatsApp Image 2026-07-26 at 18.50.40.jpeg",
    website_url: "https://elitecastlejaisalmer.com",
    booking_url: "https://elitecastlejaisalmer.com/booking",
    contact_phone: "+91-9829038039",
    contact_email: "info@elitecastlejaisalmer.com",
    whatsapp_number: "+919829038039",
    address: "Near Jaisalmer Fort, Jaisalmer, Rajasthan 345001",
    google_maps_url: "https://maps.google.com/?q=Elite+Castle+Jaisalmer",
    google_maps_embed: null,
    average_rating: 4.8,
    total_reviews: 280,
    is_active: true,
    order: 2,
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
  },
  {
    id: 3,
    name: "Happy Adventure Camp Jaisalmer",
    slug: "happy-adventure",
    description: "Happy Adventure Camp Jaisalmer offers the ultimate luxury desert camping experience in the Thar Desert. Enjoy traditional Rajasthani cultural performances, camel safaris at sunset, jeep safaris across golden dunes, and comfortable Swiss tents.",
    short_description: "Luxury desert camp with cultural programs, camel safaris & overnight camping.",
    logo_url: null,
    hero_image_url: "/businesses/happy-adventure-camp/DSC02608_1024x683.webp",
    website_url: "https://happyadventurecampjaisalmer.com",
    booking_url: "https://happyadventurecampjaisalmer.com/booking",
    contact_phone: "+91-9829038039",
    contact_email: "info@happyadventurecampjaisalmer.com",
    whatsapp_number: "+919829038039",
    address: "Sam Sand Dunes, Jaisalmer, Rajasthan 345001",
    google_maps_url: "https://maps.google.com/?q=Happy+Adventure+Camp+Jaisalmer",
    google_maps_embed: null,
    average_rating: 4.9,
    total_reviews: 420,
    is_active: true,
    order: 3,
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
  },
  {
    id: 4,
    name: "Elite India Tour Planner",
    slug: "tour-planner",
    description: "Elite India Tour Planner specializes in crafting customized travel experiences across Rajasthan and India. From private luxury tours to budget-friendly group packages, we handle every detail.",
    short_description: "Professional Rajasthan tour planning with customized packages.",
    logo_url: null,
    hero_image_url: "/businesses/elite-india-tour-planner/dheeraj-purohit.webp",
    website_url: "https://eliteindiatourplanner.com",
    booking_url: "https://eliteindiatourplanner.com/booking",
    contact_phone: "+91-9829038039",
    contact_email: "info@eliteindiatourplanner.com",
    whatsapp_number: "+919829038039",
    address: "Jaisalmer, Rajasthan 345001",
    google_maps_url: "https://maps.google.com/?q=Elite+India+Tour+Planner",
    google_maps_embed: null,
    average_rating: 4.9,
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
  },
  {
    id: 5,
    name: "Hotel Jaisal Inn",
    slug: "jaisal-inn",
    description: "Hotel Jaisal Inn is a premium hotel located near Gadisar Road in Jaisalmer offering luxury accommodation, rooftop restaurant, swimming pool, family rooms, desert safari packages and complete hospitality services.",
    short_description: "Premium hotel near Gadisar Road with rooftop restaurant, pool & safari packages.",
    logo_url: null,
    hero_image_url: "/businesses/elite-castle/WhatsApp Image 2026-07-26 at 18.50.43.jpeg",
    website_url: "https://jaisalinnjaisalmer.com/",
    booking_url: "https://jaisalinnjaisalmer.com/booking",
    contact_phone: "+91-9829038039",
    contact_email: "info@jaisalinnjaisalmer.com",
    whatsapp_number: "+919829038039",
    address: "Near Gadisar Road, Jaisalmer, Rajasthan 345001",
    google_maps_url: "https://maps.google.com/?q=Hotel+Jaisal+Inn+Jaisalmer",
    google_maps_embed: null,
    average_rating: 4.8,
    total_reviews: 150,
    is_active: true,
    order: 5,
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
  },
  {
    id: 6,
    name: "Vijay Bagh",
    slug: "vijay-bagh",
    description: "Vijay Bagh is a luxury heritage village resort near Kuldhara offering heritage suites, luxury desert camps, authentic Rajasthani hospitality, traditional dining and cultural experiences.",
    short_description: "Luxury heritage village resort near Kuldhara with heritage suites & desert camps.",
    logo_url: null,
    hero_image_url: "/businesses/mr-desert/6-scaled-e1756826347412.webp",
    website_url: "https://www.vijaybagh.com/",
    booking_url: "https://www.vijaybagh.com/booking",
    contact_phone: "+91-9829038039",
    contact_email: "info@vijaybagh.com",
    whatsapp_number: "+919829038039",
    address: "Near Kuldhara Village, Jaisalmer, Rajasthan 345001",
    google_maps_url: "https://maps.google.com/?q=Vijay+Bagh+Resort+Jaisalmer",
    google_maps_embed: null,
    average_rating: 4.9,
    total_reviews: 210,
    is_active: true,
    order: 6,
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
  },
];

export const FALLBACK_REVIEWS: Review[] = [
  {
    id: 101,
    business_id: 1,
    business_name: "Mr. Desert Jaisalmer",
    business_slug: "mr-desert",
    guest_name: "Rajesh Sharma",
    guest_email: null,
    guest_photo_url: null,
    country: "India",
    city: "Mumbai",
    visit_date: "2026-01-15",
    overall_rating: 5,
    staff_rating: 5,
    cleanliness_rating: 5,
    food_rating: 5,
    location_rating: 5,
    experience_rating: 5,
    value_for_money: 5,
    title: "Best desert experience in Jaisalmer!",
    content: "Mr. Desert made our Jaisalmer trip unforgettable. The camel safari at sunset was magical, and the camp staff were incredibly welcoming. Highly recommended!",
    is_recommended: true,
    is_verified: true,
    is_featured: true,
    is_published: true,
    is_pinned: true,
    status: "approved",
    review_source: "website",
    helpful_count: 14,
    media: [
      {
        id: 1011,
        review_id: 101,
        media_type: "image",
        url: "/businesses/mr-desert/6-scaled-e1756826347412.webp",
        width: 1024,
        height: 683,
      },
      {
        id: 1012,
        review_id: 101,
        media_type: "image",
        url: "/businesses/mr-desert/IMG-20250826-WA0122_1024x683.webp",
        width: 1024,
        height: 683,
      },
    ],
    reply: {
      id: 1,
      content: "Thank you, Rajesh! We're thrilled you enjoyed the desert experience. Hope to welcome you back soon!",
      created_at: "2026-02-11T10:00:00Z",
      updated_at: "2026-02-11T10:00:00Z",
    },
    created_at: "2026-02-10T10:00:00Z",
    updated_at: "2026-02-10T10:00:00Z",
  },
  {
    id: 102,
    business_id: 1,
    business_name: "Mr. Desert Jaisalmer",
    business_slug: "mr-desert",
    guest_name: "Sarah Johnson",
    guest_email: null,
    guest_photo_url: null,
    country: "United Kingdom",
    city: "London",
    visit_date: "2026-01-20",
    overall_rating: 5,
    staff_rating: 5,
    cleanliness_rating: 5,
    food_rating: 5,
    location_rating: 5,
    experience_rating: 5,
    value_for_money: 5,
    title: "Magical stay in the desert",
    content: "Staying with Mr. Desert was the highlight of our Rajasthan trip. The luxury tents were far better than expected, and the staff went above and beyond.",
    is_recommended: true,
    is_verified: true,
    is_featured: true,
    is_published: true,
    is_pinned: false,
    status: "approved",
    review_source: "website",
    helpful_count: 9,
    media: [
      {
        id: 1021,
        review_id: 102,
        media_type: "image",
        url: "/businesses/mr-desert/mr-desert-story.jpg",
        width: 1024,
        height: 683,
      },
    ],
    reply: null,
    created_at: "2026-02-12T14:30:00Z",
    updated_at: "2026-02-12T14:30:00Z",
  },
  {
    id: 103,
    business_id: 2,
    business_name: "Elite Castle Jaisalmer",
    business_slug: "elite-castle",
    guest_name: "Amit Kumar",
    guest_email: null,
    guest_photo_url: null,
    country: "India",
    city: "Delhi",
    visit_date: "2026-02-01",
    overall_rating: 5,
    staff_rating: 5,
    cleanliness_rating: 5,
    food_rating: 5,
    location_rating: 5,
    experience_rating: 5,
    value_for_money: 5,
    title: "Royal treatment at its finest",
    content: "Elite Castle is a gem in Jaisalmer! The hotel architecture is stunning, the rooms are spacious, and the rooftop restaurant offers an amazing view of the fort.",
    is_recommended: true,
    is_verified: true,
    is_featured: true,
    is_published: true,
    is_pinned: false,
    status: "approved",
    review_source: "website",
    helpful_count: 11,
    media: [
      {
        id: 1031,
        review_id: 103,
        media_type: "image",
        url: "/businesses/elite-castle/WhatsApp Image 2026-07-26 at 18.50.40.jpeg",
        width: 1200,
        height: 800,
      },
      {
        id: 1032,
        review_id: 103,
        media_type: "image",
        url: "/businesses/elite-castle/elite_castle_family02.webp",
        width: 1200,
        height: 800,
      },
      {
        id: 1033,
        review_id: 103,
        media_type: "image",
        url: "/businesses/elite-castle/elite_castle_family05.webp",
        width: 1200,
        height: 800,
      },
    ],
    reply: null,
    created_at: "2026-02-15T09:15:00Z",
    updated_at: "2026-02-15T09:15:00Z",
  },
  {
    id: 104,
    business_id: 3,
    business_name: "Happy Adventure Camp Jaisalmer",
    business_slug: "happy-adventure",
    guest_name: "Vikram Singh",
    guest_email: null,
    guest_photo_url: null,
    country: "India",
    city: "Jaipur",
    visit_date: "2026-02-05",
    overall_rating: 5,
    staff_rating: 5,
    cleanliness_rating: 5,
    food_rating: 5,
    location_rating: 5,
    experience_rating: 5,
    value_for_money: 5,
    title: "Ultimate desert camping!",
    content: "Happy Adventure Camp exceeded all expectations. The luxury tents are incredibly comfortable. Camel safari at sunset was the perfect end to the day!",
    is_recommended: true,
    is_verified: true,
    is_featured: true,
    is_published: true,
    is_pinned: false,
    status: "approved",
    review_source: "website",
    helpful_count: 18,
    media: [
      {
        id: 1041,
        review_id: 104,
        media_type: "image",
        url: "/businesses/happy-adventure-camp/DSC02608_1024x683.webp",
        width: 1024,
        height: 683,
      },
      {
        id: 1042,
        review_id: 104,
        media_type: "image",
        url: "/businesses/happy-adventure-camp/E-1_1024x698.webp",
        width: 1024,
        height: 698,
      },
      {
        id: 1043,
        review_id: 104,
        media_type: "image",
        url: "/businesses/happy-adventure-camp/IMG-20251201-WA0045.webp",
        width: 1024,
        height: 683,
      },
    ],
    reply: null,
    created_at: "2026-02-18T18:20:00Z",
    updated_at: "2026-02-18T18:20:00Z",
  },
  {
    id: 105,
    business_id: 4,
    business_name: "Elite India Tour Planner",
    business_slug: "tour-planner",
    guest_name: "Rohan Mehta",
    guest_email: null,
    guest_photo_url: null,
    country: "India",
    city: "Mumbai",
    visit_date: "2026-02-10",
    overall_rating: 5,
    staff_rating: 5,
    cleanliness_rating: 5,
    food_rating: 5,
    location_rating: 5,
    experience_rating: 5,
    value_for_money: 5,
    title: "Flawless Rajasthan trip planning",
    content: "Elite India Tour Planner organized our 10-day Rajasthan trip and everything was flawless. From hotel bookings to guided tours, every detail was taken care of.",
    is_recommended: true,
    is_verified: true,
    is_featured: true,
    is_published: true,
    is_pinned: false,
    status: "approved",
    review_source: "website",
    helpful_count: 7,
    media: [
      {
        id: 1051,
        review_id: 105,
        media_type: "image",
        url: "/businesses/elite-india-tour-planner/tour-planner-story.webp",
        width: 1200,
        height: 800,
      },
      {
        id: 1052,
        review_id: 105,
        media_type: "image",
        url: "/businesses/elite-india-tour-planner/camel-safari.webp",
        width: 1200,
        height: 800,
      },
    ],
    reply: null,
    created_at: "2026-02-20T11:45:00Z",
    updated_at: "2026-02-20T11:45:00Z",
  },
  {
    id: 106,
    business_id: 5,
    business_name: "Hotel Jaisal Inn",
    business_slug: "jaisal-inn",
    guest_name: "Pooja Verma",
    guest_email: null,
    guest_photo_url: null,
    country: "India",
    city: "Ahmedabad",
    visit_date: "2026-02-12",
    overall_rating: 5,
    staff_rating: 5,
    cleanliness_rating: 5,
    food_rating: 5,
    location_rating: 5,
    experience_rating: 5,
    value_for_money: 5,
    title: "Wonderful hospitality near Gadisar Road",
    content: "Hotel Jaisal Inn was a delightful stay for our family. Clean rooms, refreshing swimming pool, delicious rooftop food, and excellent desert safari arrangements by the staff.",
    is_recommended: true,
    is_verified: true,
    is_featured: true,
    is_published: true,
    is_pinned: false,
    status: "approved",
    review_source: "website",
    helpful_count: 12,
    media: [
      {
        id: 1061,
        review_id: 106,
        media_type: "image",
        url: "/businesses/elite-castle/WhatsApp Image 2026-07-26 at 18.50.43.jpeg",
        width: 1200,
        height: 800,
      },
    ],
    reply: null,
    created_at: "2026-02-22T14:10:00Z",
    updated_at: "2026-02-22T14:10:00Z",
  },
  {
    id: 107,
    business_id: 6,
    business_name: "Vijay Bagh",
    business_slug: "vijay-bagh",
    guest_name: "Karan Singhania",
    guest_email: null,
    guest_photo_url: null,
    country: "India",
    city: "Chandigarh",
    visit_date: "2026-02-14",
    overall_rating: 5,
    staff_rating: 5,
    cleanliness_rating: 5,
    food_rating: 5,
    location_rating: 5,
    experience_rating: 5,
    value_for_money: 5,
    title: "Unmatched heritage resort experience near Kuldhara",
    content: "Vijay Bagh is a tranquil sanctuary in the desert. The heritage suites and traditional cultural evening near Kuldhara made our holiday deeply memorable.",
    is_recommended: true,
    is_verified: true,
    is_featured: true,
    is_published: true,
    is_pinned: false,
    status: "approved",
    review_source: "website",
    helpful_count: 15,
    media: [
      {
        id: 1071,
        review_id: 107,
        media_type: "image",
        url: "/businesses/mr-desert/6-scaled-e1756826347412.webp",
        width: 1200,
        height: 800,
      },
    ],
    reply: null,
    created_at: "2026-02-24T16:45:00Z",
    updated_at: "2026-02-24T16:45:00Z",
  },
];

export const FALLBACK_BLOGS: ContentItem[] = [
  {
    id: 1,
    title: "Best Time to Visit Jaisalmer",
    slug: "best-time-to-visit-jaisalmer",
    excerpt: "Plan around golden light, cool desert evenings and the cultural calendar.",
    content: "Jaisalmer is at its most inviting between October and March, when the days are bright and the desert nights are made for a campfire. Build in time for the fort at sunrise, a dune sunset and an unhurried evening in the old city.\n\nDuring winter, temperatures range between 10°C and 25°C, providing ideal conditions for camel safaris, quad biking, and exploring the Golden Fort's living lanes.",
    hero_image_url: "/businesses/mr-desert/IMG-20250826-WA0122_1024x683.webp",
    author: "Mr. Desert Editorial",
    reading_time: 6,
    category: "Travel planning",
    tags: "Jaisalmer, Rajasthan, Travel Guide",
    map_url: null,
    seo_title: "Best Time to Visit Jaisalmer | Climate & Festival Guide",
    meta_description: "Discover the best months to visit Jaisalmer, Rajasthan. Learn about weather, desert safari conditions, and cultural events.",
    status: "published",
    published_at: "2026-01-10T00:00:00Z",
  },
  {
    id: 2,
    title: "A First-Timer's Guide to a Desert Camp",
    slug: "first-timers-guide-desert-camp",
    excerpt: "Everything to know before your first night under the Thar sky.",
    content: "A desert camp is more than a room in the dunes. Expect warm hospitality, local food, folk music and a slower rhythm. Pack light layers, comfortable shoes and curiosity; the best moments usually happen between the planned activities.\n\nAt Sam Sand Dunes, luxury Swiss tents provide ensuite bathrooms, plush beds, and Rajasthani hospitality combined with bonfire folk dances.",
    hero_image_url: "/businesses/happy-adventure-camp/E-1_1024x698.webp",
    author: "Mr. Desert Editorial",
    reading_time: 5,
    category: "Desert experiences",
    tags: "Desert Camp, Sam Sand Dunes, Camping",
    map_url: null,
    seo_title: "First-Timer's Guide to Jaisalmer Desert Camping",
    meta_description: "Essential tips for your first luxury desert camp experience in Jaisalmer's Thar Desert. What to pack, expected activities, and safari advice.",
    status: "published",
    published_at: "2026-01-15T00:00:00Z",
  },
  {
    id: 3,
    title: "Jaisalmer Fort: A Living Heritage",
    slug: "jaisalmer-fort-living-heritage",
    excerpt: "Walk the honey-coloured lanes of one of Rajasthan's great living forts.",
    content: "Jaisalmer Fort changes character throughout the day. Begin early for quiet lanes and soft light, pause for a rooftop view, and leave time for the homes, temples, craftspeople and stories that make the fort feel lived-in rather than museum-like.\n\nBuilt in 1156 AD by Rawal Jaisal, Sonar Qila (Golden Fort) houses over a quarter of the old city's population amidst ancient havelis and intricate Jain temples.",
    hero_image_url: "/businesses/elite-castle/WhatsApp Image 2026-07-26 at 18.50.40.jpeg",
    author: "Mr. Desert Editorial",
    reading_time: 7,
    category: "Culture & history",
    tags: "Jaisalmer Fort, Heritage, Architecture",
    map_url: null,
    seo_title: "Jaisalmer Fort Guide | Exploring Sonar Qila",
    meta_description: "Complete guide to exploring Jaisalmer's living Golden Fort (Sonar Qila). Rooftop viewpoints, Jain temples, and heritage history.",
    status: "published",
    published_at: "2026-01-20T00:00:00Z",
  },
  {
    id: 4,
    title: "Camel Safari or Jeep Safari?",
    slug: "camel-safari-or-jeep-safari",
    excerpt: "Choose the desert adventure that matches your travel style.",
    content: "Camel safaris invite you to slow down and watch the dunes unfold. Jeep safaris cover more ground and bring a sense of movement and discovery. If time allows, combine both: a late-afternoon drive followed by a quiet camel ride into sunset.\n\nDune bashing in 4x4 open jeeps across Sam Sand Dunes offers high thrill, while camel rides offer tranquil sunset views.",
    hero_image_url: "/businesses/elite-india-tour-planner/camel-safari.webp",
    author: "Mr. Desert Editorial",
    reading_time: 4,
    category: "Experiences",
    tags: "Camel Safari, Jeep Safari, Thar Desert",
    map_url: null,
    seo_title: "Camel Safari vs Jeep Safari in Jaisalmer | Adventure Guide",
    meta_description: "Compare camel safaris and jeep dune bashing in Jaisalmer. Find the best desert safari experience for your travel style.",
    status: "published",
    published_at: "2026-01-25T00:00:00Z",
  },
  {
    id: 5,
    title: "Luxury Stays Near Gadisar Lake & Road",
    slug: "luxury-stays-near-gadisar-lake-road",
    excerpt: "Why staying near Gadisar Road gives you easy access to history and serenity.",
    content: "Gadisar Road is one of the most serene locations in Jaisalmer, offering proximity to Gadisar Lake while keeping you connected to the city center. At Hotel Jaisal Inn, guests experience rooftop dining with lake views and modern luxury amenities.",
    hero_image_url: "/businesses/elite-castle/WhatsApp Image 2026-07-26 at 18.50.43.jpeg",
    author: "Hotel Jaisal Inn Desk",
    reading_time: 5,
    category: "Hospitality & Stays",
    tags: "Hotel Jaisal Inn, Gadisar Road, Jaisalmer Hotel",
    map_url: null,
    seo_title: "Luxury Accommodation Near Gadisar Road Jaisalmer",
    meta_description: "Explore premium accommodation, swimming pool facilities, and safari bookings at Hotel Jaisal Inn Jaisalmer.",
    status: "published",
    published_at: "2026-01-28T00:00:00Z",
  },
  {
    id: 6,
    title: "Discovering Kuldhara & Village Resort Living",
    slug: "discovering-kuldhara-village-resort-living",
    excerpt: "Step into the mystery of Kuldhara village while relaxing in heritage luxury.",
    content: "Vijay Bagh resort offers an authentic taste of Rajasthani village life combined with royal heritage suites. Located near the ghost village of Kuldhara, it provides serene desert solitude, traditional dining, and star-filled skies.",
    hero_image_url: "/businesses/mr-desert/6-scaled-e1756826347412.webp",
    author: "Vijay Bagh Editorial",
    reading_time: 6,
    category: "Heritage & Resorts",
    tags: "Vijay Bagh, Kuldhara, Heritage Resort",
    map_url: null,
    seo_title: "Vijay Bagh Heritage Resort | Luxury Near Kuldhara Jaisalmer",
    meta_description: "Experience Rajasthani heritage suites and village resort hospitality at Vijay Bagh near Kuldhara Village, Jaisalmer.",
    status: "published",
    published_at: "2026-01-30T00:00:00Z",
  },
];

export const FALLBACK_GUIDES: ContentItem[] = [
  {
    id: 101,
    title: "Jaisalmer Fort Guide",
    slug: "jaisalmer-fort-guide",
    excerpt: "History, viewpoints and practical tips for exploring the Golden Fort.",
    content: "Start early, wear comfortable footwear and take time to look beyond the main viewpoints. The fort's lanes reward a slow walk, especially around the temples, carved facades and small craft studios.",
    hero_image_url: "/businesses/mr-desert/6-scaled-e1756826347412.webp",
    author: "Mr. Desert Editorial",
    reading_time: 5,
    category: "Heritage",
    tags: "Fort, History, Views",
    map_url: null,
    seo_title: "Jaisalmer Fort Destination Guide | Sightseeing & Tips",
    meta_description: "Comprehensive destination guide for visiting Jaisalmer Fort (Sonar Qila). Entrance details, best photography spots, and history.",
    status: "published",
    published_at: "2026-01-05T00:00:00Z",
  },
  {
    id: 102,
    title: "Sam Sand Dunes Guide",
    slug: "sam-sand-dunes-guide",
    excerpt: "How to plan a memorable sunset and desert evening at Sam.",
    content: "Arrive before sunset so you can settle into the landscape rather than rush through it. A good evening pairs a dune experience with local food, music and enough quiet to notice the sky after dark.",
    hero_image_url: "/businesses/happy-adventure-camp/DSC02608_1024x683.webp",
    author: "Mr. Desert Editorial",
    reading_time: 6,
    category: "Desert",
    tags: "Sam Dunes, Sunset, Desert",
    map_url: null,
    seo_title: "Sam Sand Dunes Jaisalmer Guide | Safaris & Camps",
    meta_description: "Explore Sam Sand Dunes in Jaisalmer. Detailed guide for desert safaris, sunset points, and evening cultural programs.",
    status: "published",
    published_at: "2026-01-08T00:00:00Z",
  },
  {
    id: 103,
    title: "Gadisar Lake Guide",
    slug: "gadisar-lake-guide",
    excerpt: "A peaceful morning stop framed by temples, chhatris and old-city stories.",
    content: "Gadisar Lake is best experienced in the softer morning light. Walk the edges, notice the carved details and use the visit as a gentle introduction to the layered history of Jaisalmer.",
    hero_image_url: "/businesses/elite-castle/WhatsApp Image 2026-07-26 at 18.50.43.jpeg",
    author: "Mr. Desert Editorial",
    reading_time: 4,
    category: "Places to visit",
    tags: "Gadisar Lake, Boating, Heritage",
    map_url: null,
    seo_title: "Gadisar Lake Jaisalmer Guide | Morning Walks & Boating",
    meta_description: "Visitor guide for Gadisar Lake, Jaisalmer. Discover morning boating, historic archways (Tilon Ki Pol), and migratory birds.",
    status: "published",
    published_at: "2026-01-12T00:00:00Z",
  },
  {
    id: 104,
    title: "Camel Safari Guide",
    slug: "camel-safari-guide",
    excerpt: "What to expect, what to bring and how to choose your pace.",
    content: "Choose a safari operator that treats the animals well and keeps the group size comfortable. Bring sun protection, water and a light layer for the evening; the desert is generous when you give it time.",
    hero_image_url: "/businesses/elite-india-tour-planner/tour-safari.webp",
    author: "Mr. Desert Editorial",
    reading_time: 5,
    category: "Experiences",
    tags: "Camel Ride, Thar Desert, Safari",
    map_url: null,
    seo_title: "Jaisalmer Camel Safari Guide | Sunset & Overnights",
    meta_description: "Everything you need to know about booking a camel safari in Jaisalmer. Safety tips, packing list, and recommended routes.",
    status: "published",
    published_at: "2026-01-18T00:00:00Z",
  },
  {
    id: 105,
    title: "Kuldhara Heritage Guide",
    slug: "kuldhara-heritage-guide",
    excerpt: "Explore the abandoned Paliwal Brahmin village and its mysterious legends.",
    content: "Located near Vijay Bagh resort, Kuldhara is an 800-year-old abandoned village steeped in folklore and architectural remnants. A morning visit provides unmatched insight into ancient water harvesting and Rajasthani history.",
    hero_image_url: "/businesses/mr-desert/6-scaled-e1756826347412.webp",
    author: "Vijay Bagh Travel Guide",
    reading_time: 6,
    category: "Heritage",
    tags: "Kuldhara, Heritage, Vijay Bagh",
    map_url: null,
    seo_title: "Kuldhara Ghost Village Jaisalmer | Travel Guide & History",
    meta_description: "Complete guide to visiting Kuldhara Village near Vijay Bagh Resort in Jaisalmer. History, myths, and photography tips.",
    status: "published",
    published_at: "2026-01-22T00:00:00Z",
  },
];

